import type { Metadata } from 'next'
import { NextIntlClientProvider } from 'next-intl'
import { getMessages } from 'next-intl/server'
import { ToastContainer } from 'react-toastify'
import Providers from './providers'
import Chat from '@/components/chat'
import { RootLayoutProps } from '@/types/layout'
import 'react-toastify/dist/ReactToastify.css'
import './globals.css'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({ children, params: { locale } }: Readonly<RootLayoutProps>) {
  const messages = await getMessages()
  return (
    <html lang={locale}>
      <body suppressHydrationWarning={true} className="w-screen overflow-x-hidden">
        <Providers>
          <NextIntlClientProvider locale={locale} messages={messages}>
            {children}
          </NextIntlClientProvider>
          <ToastContainer
            position="top-right"
            autoClose={3000}
            hideProgressBar={false}
            newestOnTop={false}
            closeOnClick
            rtl={false}
            pauseOnFocusLoss
            draggable
            pauseOnHover
            theme="light"
          />

          <Chat />
        </Providers>
      </body>
    </html>
  )
}
