import type { Metadata } from 'next'
import Providers from './providers'
import { ToastContainer } from 'react-toastify';
import "react-toastify/dist/ReactToastify.css";
import Chat from '@/components/chat';
import './globals.css'
import { RootLayoutProps } from '@/types/layout';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
  params: {locale}
}: Readonly<RootLayoutProps>) {
  return (
    <html lang={locale}>
      <body suppressHydrationWarning={true} className="w-screen overflow-x-hidden">
        <Providers>
          {children}
          <ToastContainer
            position="top-right"
            autoClose={3000}
            hideProgressBar={false}
            newestOnTop={false}
            closeOnClick
            rtl={false}
            pauseOnFocusLoss
            draggable
            pauseOnHover
            theme="light"
          />

          <Chat />
        </Providers>
      </body>
    </html>
  )
}
